framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~

    #esi: true
    #fragments: true
    php_errors:
        log: true

    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        prefix_seed: gamiphier/api-command

        # Redis
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'
        pools:
            app.cache.api_token:
                adapter: cache.app
                default_lifetime: 3600
